const seed=[
 {id:'JNIT-2608-001',customer:'Namgola Logistics',file:'NLG86472240.pdf',status:'received',contact:'Anna Mokoena',email:'anna@namgola.example',agent:null,time:'08:42',border:'Lebombo'},
 {id:'JNIT-2608-002',customer:'ABC Logistics',file:'Commercial-Invoice.pdf',status:'progress',contact:'Peter Dlamini',email:'ops@abclogistics.example',agent:"Jacques O'Connell",time:'09:05',border:'Beitbridge'},
 {id:'JNIT-2608-003',customer:'Namgola Logistics',file:'Supporting-Pack.pdf',status:'requested',contact:'Anna Mokoena',email:'anna@namgola.example',agent:"Jacques O'Connell",time:'09:28',border:'Lebombo'},
 {id:'JNIT-2608-004',customer:'Namgola Logistics',file:'Completed-Clearance.pdf',status:'completed',contact:'Anna Mokoena',email:'anna@namgola.example',agent:'Sarah Nkosi',time:'10:11',border:'Skilpadshek'}
];
let jobs=JSON.parse(localStorage.getItem('jnitJobs')||'null')||seed;let audit=JSON.parse(localStorage.getItem('jnitAudit')||'null')||[{text:'POC workspace opened',time:'Today, 08:30'}];
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
const API=(window.APP_CONFIG&&window.APP_CONFIG.apiUrl)||'';
async function api(path,options={}){if(!API)return null;let r=await fetch(API+path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});if(!r.ok)throw new Error((await r.json()).message||'Request failed');return r.json()}
const statusInfo={received:['Received','red'],progress:['In progress','blue'],requested:['Awaiting documents','amber'],completed:['Completed','green']};
function save(){localStorage.setItem('jnitJobs',JSON.stringify(jobs));localStorage.setItem('jnitAudit',JSON.stringify(audit));render()}
function log(text){audit.unshift({text,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})});audit=audit.slice(0,12)}
function card(j,actions=''){let [label,color]=statusInfo[j.status];return `<article class="job-card ${color}"><div class="ref">${j.id}</div><div class="customer">${j.customer}</div><div class="meta">${j.file}<br>${j.border} · ${j.time}${j.agent?`<br>Agent: ${j.agent}`:''}</div>${actions}</article>`}
function render(){
 const counts=s=>jobs.filter(j=>j.status===s).length;
 $('#metrics').innerHTML=[['Incoming',counts('received'),'Awaiting acceptance'],['In progress',counts('progress'),'Assigned to agents'],['Customer action',counts('requested'),'Documents requested'],['Completed',counts('completed'),'Ready / returned']].map(x=>`<article><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('');
 const lanes=[['received','Incoming'],['progress','Processing'],['requested','Customer action'],['completed','Completed']];
 $('#trackingBoard').innerHTML=lanes.map(([s,n])=>`<div class="lane"><div class="lane-head">${n}<span>${counts(s)}</span></div>${jobs.filter(j=>j.status===s).map(j=>card(j)).join('')||'<p class="muted">No jobs</p>'}</div>`).join('');
 $('#incomingList').innerHTML=jobs.filter(j=>j.status==='received').map(j=>`<div class="list-card"><div><h3>${j.id} · ${j.customer}</h3><p>${j.file} · Received ${j.time}</p></div><button class="primary small" onclick="acceptJob('${j.id}')">Accept job</button></div>`).join('')||'<div class="list-card"><p>Incoming queue is clear.</p></div>';
 $('#activeList').innerHTML=jobs.filter(j=>j.agent==="Jacques O'Connell"&&j.status!=='completed').map(j=>`<div class="list-card"><div><h3>${j.id} · ${statusInfo[j.status][0]}</h3><p>${j.customer} · ${j.file}</p></div><div class="list-actions">${j.status==='progress'?`<button class="outline small" onclick="requestDocs('${j.id}')">Request files</button>`:''}<button class="primary small" onclick="completeJob('${j.id}')">Complete</button></div></div>`).join('')||'<div class="list-card"><p>No active work assigned.</p></div>';
 $('#customerJobs').innerHTML=jobs.filter(j=>j.customer==='Namgola Logistics').map(j=>`<div class="list-card"><div><h3>${j.id}</h3><p>${j.file} · ${statusInfo[j.status][0]}${j.agent?` · ${j.agent}`:''}</p></div>${j.status==='requested'?`<button class="primary small" onclick="uploadRequested('${j.id}')">Upload requested file</button>`:''}</div>`).join('');
 $('#customerMessages').innerHTML=jobs.filter(j=>j.status==='requested').map(j=>`<div class="message"><strong>Additional document required</strong><br>Please upload the certificate of origin against ${j.id}.<small>${j.agent} · Today</small></div>`).join('')||'<p class="muted">No outstanding requests.</p>';
 $('#auditLog').innerHTML=audit.map(a=>`<div class="audit-item">${a.text}<small>${a.time}</small></div>`).join(''); $('#auditCount').textContent=audit.length; $('#updatedAt').textContent='Updated '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
}
async function updateJob(id,changes){if(API)await api('/jobs/'+id,{method:'PATCH',body:JSON.stringify(changes)});let j=jobs.find(x=>x.id===id);Object.assign(j,changes);if(changes.agent_name)j.agent=changes.agent_name;save()}
window.acceptJob=async id=>{await updateJob(id,{status:'progress',agent_name:"Jacques O'Connell",agent_id:'EMP-014'});log(`${id} accepted by Jacques O'Connell (EMP-014)`);save();toast('Job moved to your processing queue')};
window.requestDocs=async id=>{await updateJob(id,{status:'requested'});log(`Additional documents requested for ${id}`);save();toast('Customer notified and upload linked to this job')};
window.completeJob=async id=>{let j=jobs.find(x=>x.id===id);await updateJob(id,{status:'completed'});log(`${id} marked complete by ${j.agent}`);save();toast('Job completed and ready for return')};
window.uploadRequested=id=>{let j=jobs.find(x=>x.id===id);j.status='progress';log(`Requested document uploaded to existing job ${id}`);save();toast(`Upload attached to ${id}; assigned agent notified`)};
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');let names={tracking:['LIVE OPERATIONS','Document tracking board'],agent:['AGENT WORKSPACE','My document queue'],customer:['CUSTOMER SELF-SERVICE','Track and upload documents'],admin:['MANAGEMENT & CONTROL','Administration portal']};$('#eyebrow').textContent=names[b.dataset.view][0];$('#pageTitle').textContent=names[b.dataset.view][1]});
const dlg=$('#uploadDialog');$('#openUpload').onclick=()=>dlg.showModal();$('#closeUpload').onclick=$('#cancelUpload').onclick=()=>dlg.close();
$('#uploadForm').onsubmit=async e=>{e.preventDefault();let fd=new FormData(e.target),file=fd.get('document'),created;if(API){created=await api('/jobs',{method:'POST',body:JSON.stringify({customer:fd.get('customer'),contact:fd.get('contact'),email:fd.get('email'),filename:file.name,content_type:file.type||'application/octet-stream',border:fd.get('border'),origin:fd.get('origin'),notes:fd.get('notes')})});let put=await fetch(created.upload_url,{method:'PUT',headers:{'content-type':file.type||'application/octet-stream'},body:file});if(!put.ok)throw new Error('Document upload failed')}let id=created?created.job.job_id:'JNIT-2608-'+String(Math.max(...jobs.map(j=>+j.id.split('-').pop()))+1).padStart(3,'0');jobs.unshift({id,customer:fd.get('customer'),file:file.name,status:'received',contact:fd.get('contact'),email:fd.get('email'),agent:null,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),border:fd.get('border')});log(`${id} created by customer portal upload`);save();dlg.close();toast(`Upload received — tracking reference ${id}`)};
$('#resetDemo').onclick=()=>{jobs=structuredClone(seed);audit=[{text:'Demo data reset',time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}];save();toast('Demo restored')};
async function start(){if(API){try{let data=await api('/jobs');if(data.items.length)jobs=data.items.map(j=>({...j,id:j.job_id,file:j.filename,agent:j.agent_name||null,time:new Date(j.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}))}catch(e){toast('AWS API unavailable — showing demo data')}}render()}start();
